// File generated by FlutterFire CLI.
// Updated with real Firebase configuration for kachuful-88b5c project
// Project ID: kachuful-88b5c

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XBfGUjrYGAgsZDgTZSfG0mKy7BSV0X8',
    appId: '1:855206596279:web:5df43238969eb6ddb54732',
    messagingSenderId: '855206596279',
    projectId: 'kachuful-88b5c',
    authDomain: 'kachuful-88b5c.firebaseapp.com',
    storageBucket: 'kachuful-88b5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoM4S5kBzD2x9soKRoe_Wdl9dQHvxtpmc',
    appId: '1:855206596279:android:c635a01a40687e44b54732',
    messagingSenderId: '855206596279',
    projectId: 'kachuful-88b5c',
    storageBucket: 'kachuful-88b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKNCSzwuxScA-0VCcsxf9YZSdIpfTi_KA',
    appId: '1:855206596279:ios:22672f94ec509dfab54732',
    messagingSenderId: '855206596279',
    projectId: 'kachuful-88b5c',
    storageBucket: 'kachuful-88b5c.firebasestorage.app',
    iosBundleId: 'com.example.kachuful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKNCSzwuxScA-0VCcsxf9YZSdIpfTi_KA',
    appId: '1:855206596279:ios:22672f94ec509dfab54732',
    messagingSenderId: '855206596279',
    projectId: 'kachuful-88b5c',
    storageBucket: 'kachuful-88b5c.firebasestorage.app',
    iosBundleId: 'com.example.kachuful',
  );
}
