name: Release APK and Deploy Web

on:
  push:
    branches:
      - main

permissions:
  contents: write # needed to create releases and upload assets

jobs:
  build-release-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK (release)
        run: flutter build apk --release

      - name: Build web (release, offline-first)
        run: flutter build web --release --pwa-strategy=offline-first

      - name: Compute release tag
        id: meta
        run: echo "tag=v$(date -u +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: Kachuful Android release (${{ steps.meta.outputs.tag }})
          files: build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        if: ${{ secrets.FIREBASE_TOKEN != '' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --non-interactive

      - name: Skip Hosting deploy (no FIREBASE_TOKEN)
        if: ${{ secrets.FIREBASE_TOKEN == '' }}
        run: echo "FIREBASE_TOKEN not set; skipping Firebase Hosting deploy. Add repo secret FIREBASE_TOKEN to enable."
